activities:

  # =========================
  # Streaming RPC
  # =========================
  - application_id: "1542226742381645895"
    type: 1
    name: "feds"
    details: ""
    state: "fuck."

    largeImageKey: "feds"
    largeImageText: ""
    smallImageKey: ""
    smallImageText: ""

    url: ""

    buttons:
      - name: "rape"
        url: "https://discord.com/oauth2/authorize?client_id=1542226742381645895&permissions=8&scope=bot"


  # =========================
  # Visual Studio Code RPC
  # =========================
  - application_id: "1544210118269345902"
    type: 0
    name: "Visual Studio Code"
    details: ""
    state: "Editing malware.cpp"

    largeImageKey: "keyboard"
    largeImageText: ""
    smallImageKey: "vscode"
    smallImageText: ""

    url: ""


# =========================
# Custom Status
# =========================
custom_status: ""
custom_emoji: ""
