application_id: "1542226742381645895"

activities:

  # =========================
  # Streaming RPC
  # =========================
  - type: 1
    name: "Streaming"
    details: "feds"
    state: "fuck."

    largeImageKey: ""
    largeImageText: ""
    smallImageKey: ""
    smallImageText: ""

    url: ""

    buttons:
      - name: "rape"
        url: "https://discord.com/oauth2/authorize?client_id=1542226742381645895&permissions=8&scope=bot"


  # =========================
  # Visual Studio Code RPC
  # =========================
  - type: 0
    name: "Visual Studio Code"
    details: "Visual Studio Code"
    state: "Editing malware.cpp"

    largeImageKey: ""
    largeImageText: ""
    smallImageKey: "vscode"
    smallImageText: "Visual Studio Code"

    url: ""


# =========================
# Custom Status
# =========================
custom_status: ""
custom_emoji: ""
